name: Create new release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repository
        uses: actions/checkout@v5
      - name: get version from package.json
        uses: actions/github-script@v8
        id: version
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pkjson = require(`${process.env.GITHUB_WORKSPACE}/package.json`);
            core.info(`Version: ${pkjson.version}`);
            return pkjson.version;
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.version.outputs.result }} \
            --generate-notes \  
            --title "Release v${{ steps.version.outputs.result }}" \
            --notes "Release notes here"
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE }}
      #   with:
      #     tag_name: v${{ steps.version.outputs.result }}
      #     release_name: Release v${{ steps.version.outputs.result }}
      #     body: |
      #       Release notes can be [generated](https://github.com/semantic-release/release-notes-generator) based on commit messages etc.

      #       It is not covered in this course.
      #     draft: false
      #     prerelease: false
